name: 'cmakc'
description: 'cmak build'
inputs:
  cmake_build_type:  # id of input
    description: 'build type'
    required: true
    default: 'Release'
 
  cmake_extra_args:
    description: 'cpp compiler details'
    required: false
    default: '-DCMAKE_C_COMPILER=/usr/bin/gcc-10 -DCMAKE_CXX_COMPILER=/usr/bin/g++-10'
  
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
#     - name: Create Work Dir
#       run: mkdir build
#       shell: bash
    - name: Configure
      shell: bash
      run: |
          mkdir build
          mkdir instdir
          cmake \
            -S . \
            -B . \
            -DCMAKE_BUILD_TYPE=${{ inputs.cmake_build_type }} \
            -DCMAKE_INSTALL_PREFIX:PATH=instdir
    - name: Build
      shell: bash
      run: cmake --build . --config ${{ inputs.cmake_build_type }}
    - run: cmake .. ${{ inputs.cmake_extra_args }} -DCMAKE_BUILD_TYPE=${{ inputs.cmake_build_type }}
      shell: bash
#     - name: Build
#       working-directory: ./build
#       run: cmake --build . -j --config ${{ inputs.cmake_build_type }}
#       shell: bash
    
#     - id: random-number-generator
#       run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
#       shell: bash
#     - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
#       shell: bash
#     - run: goodbye.sh
#       shell: bash
